// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiDMw6RAcQLECgPvtwOEgAxaij27qDvvs',
    appId: '1:938406849296:web:8f11c2e602b8d2f0775395',
    messagingSenderId: '938406849296',
    projectId: 'collabothon2025-f1484',
    authDomain: 'collabothon2025-f1484.firebaseapp.com',
    storageBucket: 'collabothon2025-f1484.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD64s0J0hSHrT_bX0D-XzhE4d-zf52p7ig',
    appId: '1:938406849296:android:e0a121f2db021df0775395',
    messagingSenderId: '938406849296',
    projectId: 'collabothon2025-f1484',
    storageBucket: 'collabothon2025-f1484.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAAYgkyFUST0XhVW00OAZPaZ11-22cdDo',
    appId: '1:938406849296:ios:b269d6c5375c21cd775395',
    messagingSenderId: '938406849296',
    projectId: 'collabothon2025-f1484',
    storageBucket: 'collabothon2025-f1484.firebasestorage.app',
    iosClientId: '938406849296-53nhln2b4d84evun7o0n07set0hee0eu.apps.googleusercontent.com',
    iosBundleId: 'com.example.application',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAAYgkyFUST0XhVW00OAZPaZ11-22cdDo',
    appId: '1:938406849296:ios:b269d6c5375c21cd775395',
    messagingSenderId: '938406849296',
    projectId: 'collabothon2025-f1484',
    storageBucket: 'collabothon2025-f1484.firebasestorage.app',
    iosClientId: '938406849296-53nhln2b4d84evun7o0n07set0hee0eu.apps.googleusercontent.com',
    iosBundleId: 'com.example.application',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCiDMw6RAcQLECgPvtwOEgAxaij27qDvvs',
    appId: '1:938406849296:web:2ad56e4713562524775395',
    messagingSenderId: '938406849296',
    projectId: 'collabothon2025-f1484',
    authDomain: 'collabothon2025-f1484.firebaseapp.com',
    storageBucket: 'collabothon2025-f1484.firebasestorage.app',
  );

}